development:
  secret_key_base: <%= ('x' * 30) %>
  gmail_username: <%= ENV['GMAIL_USERNAME'] %>
  gmail_password: <%= ENV['GMAIL_PASSWORD'] %>
  s3_bucket_name: porthos
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
 
test:
  secret_key_base: <%= ('x' * 30) %>
  gmail_username: <%= ENV['GMAIL_USERNAME'] %>
  gmail_password: <%= ENV['GMAIL_PASSWORD'] %>
  s3_bucket_name: porthos
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  
   