development:
  secret_key_base: 25b5cec7e84a7d376fe6467452ef94c6c544a411983d877c4ff1a8646d3c30236539479f8a297b5359c7367d33aa99046ac5ece02d45b0115448b9c7d4ed4379
  gmail_username: development@porthoshome.com
  gmail_password: wYsrd1819
  seller_cloud_id: phillip.medrano@gmail.com
  seller_cloud_pw: 123456
  s3_bucket_name: porthos
  aws_access_key_id: AKIAJ5BI2HMLGFSWSMHA
  aws_secret_access_key: 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
 
test:
  secret_key_base: 25b5cec7e84a7d376fe6467452ef94c6c544a411983d877c4ff1a8646d3c30236539479f8a297b5359c7367d33aa99046ac5ece02d45b0115448b9c7d4ed4379
  gmail_username: development@porthoshome.com
  gmail_password: wYsrd1819
  seller_cloud_id: phillip.medrano@gmail.com
  seller_cloud_pw: 123456
  s3_bucket_name: porthos
  aws_access_key_id: AKIAJ5BI2HMLGFSWSMHA
  aws_secret_access_key: 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
  
   