sellercloud:
  wsdl:
    host: 'http://tt.ws.sellercloud.com/'
    orders:
      retrieve: scservice.asmx?WSDL
      create: OrderCreationService.asmx?WSDL
      update: scservice.asmx?WSDL
    purchase_orders: POServices.asmx?WSDL
    inventory: SCInventoryService.asmx?WSDL
    timeout: 30000

